name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch

# Add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Install project dependencies
        run: uv sync --extra all

      - name: Install doc-specific dependencies
        run: |
          uv pip install -r docs/requirements.txt

      - name: Build the documentation
        run: |
          cd docs
          rm -rf _build  # Remove existing build directory
          uv run make html
          uv run python -c "import ell; version = ell.__version__; print(version); open('_build/html/_static/ell_version.txt', 'w').write(version)"

        # env:
          # SPHINXOPTS: "-W"  # Treat warnings as errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  # Path to the built documentation
          cname: docs.ell.so
